import bcrypt from "bcryptjs";

export const MOCK_USERS = [
  {
    id: "user-student-1",
    email: "student1@exam.edu",
    password: "Student@123",
    passwordHash: "$2a$10$U4s8k8uL3K6o.5mR1q1qee0T.d0N8x.5gYvD1u8/0d2mE4f5g6h7i", // fallback
    name: "Rahul Kumar",
    role: "STUDENT",
    studentId: "student-1",
    rollNumber: "2026CS101",
    registrationNo: "REG2026001",
    departmentName: "Department of Computer Science & Engineering",
  },
  {
    id: "user-admin-1",
    email: "admin@exam.edu",
    password: "Admin@123",
    passwordHash: "$2a$10$U4s8k8uL3K6o.5mR1q1qee0T.d0N8x.5gYvD1u8/0d2mE4f5g6h7i",
    name: "Dean Academic",
    role: "ADMIN",
    departmentName: "Administration",
  },
  {
    id: "user-faculty-1",
    email: "faculty1@exam.edu",
    password: "Faculty@123",
    passwordHash: "$2a$10$U4s8k8uL3K6o.5mR1q1qee0T.d0N8x.5gYvD1u8/0d2mE4f5g6h7i",
    name: "Prof. Sharma",
    role: "FACULTY",
    facultyId: "faculty-1",
    departmentName: "Department of Computer Science & Engineering",
  },
  {
    id: "user-invigilator-1",
    email: "invigilator1@exam.edu",
    password: "Invigilator@123",
    passwordHash: "$2a$10$U4s8k8uL3K6o.5mR1q1qee0T.d0N8x.5gYvD1u8/0d2mE4f5g6h7i",
    name: "Dr. Rao",
    role: "INVIGILATOR",
    facultyId: "faculty-2",
    departmentName: "Department of Mathematics & Computing",
  },
];

export const MOCK_STUDENT_DASHBOARD = {
  student: {
    id: "student-1",
    name: "Rahul Kumar",
    email: "student1@exam.edu",
    rollNumber: "2026CS101",
    registrationNo: "REG2026001",
    semester: 4,
    department: "Department of Computer Science & Engineering",
  },
  analytics: {
    totalTaken: 3,
    passedCount: 3,
    avgPercentage: 88,
  },
  availableExams: [
    {
      id: "exam-1",
      title: "Mid-Term Examination: Java Programming",
      description: "Covers Object-Oriented Programming, Multithreading, and Exception Handling",
      code: "CS301-MID",
      subjectName: "Java Programming",
      examType: "ONLINE_OBJECTIVE",
      durationMinutes: 45,
      totalMarks: 50,
      passMarks: 20,
      negativeMarking: 0.25,
      questionCount: 25,
      attemptStatus: "NOT_STARTED",
      attemptId: null,
      resultId: null,
      score: null,
    },
    {
      id: "exam-2",
      title: "Database Management Systems Practice Test",
      description: "SQL Queries, Normalization (1NF to BCNF), and ER Diagrams",
      code: "CS302-PRAC",
      subjectName: "Database Management Systems",
      examType: "PRACTICE_TEST",
      durationMinutes: 30,
      totalMarks: 30,
      passMarks: 12,
      negativeMarking: 0.0,
      questionCount: 15,
      attemptStatus: "SUBMITTED",
      attemptId: "att-1",
      resultId: "res-1",
      score: 27,
    },
  ],
  scheduledExams: [
    {
      scheduleId: "sch-1",
      examTitle: "Final Semester Exam: Java Programming",
      examCode: "CS301-FINAL",
      subject: "Java Programming",
      date: new Date(Date.now() + 86400000 * 2).toISOString(),
      startTime: "09:30 AM",
      endTime: "11:30 AM",
      hallName: "Alan Turing Examination Hall",
      hallCode: "H-101",
      building: "Main Academic Block",
      floor: "1st Floor",
      seatNumber: "H101-R02-S05",
      attendanceStatus: "PRESENT",
      isConfirmed: true,
      confirmedAt: new Date().toISOString(),
      notes: "Verified via biometric / ID check",
    },
    {
      scheduleId: "sch-2",
      examTitle: "Final Semester Exam: DBMS",
      examCode: "CS302-FINAL",
      subject: "Database Management Systems",
      date: new Date(Date.now() + 86400000 * 5).toISOString(),
      startTime: "02:00 PM",
      endTime: "04:00 PM",
      hallName: "Ada Lovelace Examination Hall",
      hallCode: "H-102",
      building: "Science Block",
      floor: "2nd Floor",
      seatNumber: "H102-R01-S08",
      attendanceStatus: "NOT_MARKED",
      isConfirmed: false,
      confirmedAt: null,
      notes: null,
    },
  ],
  recentResults: [
    {
      id: "res-1",
      examTitle: "Database Management Systems Practice Test",
      examCode: "CS302-PRAC",
      subject: "Database Management Systems",
      score: 27,
      maxScore: 30,
      percentage: 90,
      isPassed: true,
      accuracy: 93.3,
      date: new Date(Date.now() - 86400000 * 3).toISOString(),
    },
    {
      id: "res-2",
      examTitle: "Data Structures & Algorithms Quiz",
      examCode: "CS201-QUIZ",
      subject: "Data Structures & Algorithms",
      score: 42,
      maxScore: 50,
      percentage: 84,
      isPassed: true,
      accuracy: 86.5,
      date: new Date(Date.now() - 86400000 * 10).toISOString(),
    },
  ],
  notifications: [
    {
      id: "notif-1",
      userId: "user-student-1",
      title: "Hall Ticket Released",
      message: "Your Hall Ticket for Java Programming (CS301-FINAL) is now available.",
      type: "SCHEDULE",
      isRead: false,
      createdAt: new Date().toISOString(),
    },
    {
      id: "notif-2",
      userId: "user-student-1",
      title: "Exam Result Published",
      message: "DBMS Practice Test results have been published. Score: 27/30 (90%).",
      type: "RESULT",
      isRead: true,
      createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    },
  ],
};

export const MOCK_FACULTY_DASHBOARD = {
  faculty: {
    id: "faculty-1",
    name: "Prof. Sharma",
    email: "faculty1@exam.edu",
    designation: "Assistant Professor",
    department: "Department of Computer Science & Engineering",
  },
  stats: {
    totalExamsCreated: 5,
    activeExams: 2,
    totalQuestionsInBank: 120,
    upcomingInvigilations: 2,
  },
  exams: [
    {
      id: "exam-1",
      title: "Mid-Term Examination: Java Programming",
      code: "CS301-MID",
      subjectName: "Java Programming",
      examType: "ONLINE_OBJECTIVE",
      durationMinutes: 45,
      totalMarks: 50,
      isPublished: true,
      createdAt: new Date().toISOString(),
      questionCount: 25,
      totalAttempts: 42,
    },
    {
      id: "exam-2",
      title: "Database Management Systems Practice Test",
      code: "CS302-PRAC",
      subjectName: "Database Management Systems",
      examType: "PRACTICE_TEST",
      durationMinutes: 30,
      totalMarks: 30,
      isPublished: true,
      createdAt: new Date(Date.now() - 86400000 * 7).toISOString(),
      questionCount: 15,
      totalAttempts: 38,
    },
  ],
  invigilations: [
    {
      id: "inv-1",
      examTitle: "Final Semester Exam: Java Programming",
      hallName: "Alan Turing Hall (H-101)",
      date: new Date(Date.now() + 86400000 * 2).toISOString(),
      time: "09:30 AM - 11:30 AM",
      status: "ASSIGNED",
    },
  ],
};

export const MOCK_INVIGILATOR_DASHBOARD = {
  invigilator: {
    id: "faculty-2",
    name: "Dr. Rao",
    email: "invigilator1@exam.edu",
    designation: "Associate Professor",
    department: "Department of Mathematics & Computing",
  },
  assignments: [
    {
      assignmentId: "inv-1",
      scheduleId: "sch-1",
      examTitle: "Final Semester Exam: Java Programming",
      examCode: "CS301-FINAL",
      subject: "Java Programming",
      hallName: "Alan Turing Examination Hall",
      hallCode: "H-101",
      building: "Main Academic Block",
      floor: "1st Floor",
      capacity: 40,
      allocatedCount: 35,
      date: new Date(Date.now() + 86400000 * 2).toISOString(),
      startTime: "09:30 AM",
      endTime: "11:30 AM",
      status: "ASSIGNED",
      isConfirmed: false,
      students: [
        {
          studentId: "student-1",
          name: "Rahul Kumar",
          rollNumber: "2026CS101",
          registrationNo: "REG2026001",
          seatNumber: "H101-R02-S05",
          attendanceStatus: "PRESENT",
          isConfirmed: true,
          confirmedAt: new Date().toISOString(),
          notes: null,
        },
        {
          studentId: "student-2",
          name: "Priya Verma",
          rollNumber: "2026CS102",
          registrationNo: "REG2026002",
          seatNumber: "H101-R02-S06",
          attendanceStatus: "NOT_MARKED",
          isConfirmed: false,
          confirmedAt: null,
          notes: null,
        },
      ],
    },
  ],
};
